@startuml

class Main {
}

interface Print {
    printWeek()
    printStrong()
}

class PrintBanner {
    printWeek()
    printStrong()
}
note bottom
    <size:10>Bannerクラスを継承し、Printインタフェースを
    <size:10>実装して、アダプターの役割を実現する
end note

class Banner {
    showWithParen()
    showWithAster()
}

Main -do-> Print:Users
Print <|.ri. PrintBanner:implements
PrintBanner -ri-|> Banner:extends

note left of Main
    <size:10>Client
end note

note left of Print
    <size:10>Target
end note

note top of PrintBanner
    <size:10>Adapter
end note

note top of Banner
    <size:10>Adaptee
end note

@enduml